#!/system/bin/sh
# V2T by Aditya Pratama :v
# Copyright (c) 2017 DEACE
version="1.1.07"

interface[0]="Wifi Tethering"
interface[1]="Bluetooth Tethering"
interface[2]="USB Tethering"

#V2T FUNCTION
__print () {
	sleep 0.5
	echo "$1"
}

__print "
 __     ______ _____ 
 \ \   / /___ \_   _|	VPN TO TETHER v$version
  \ \ / /  __) || |  	Author: Aditya Pratama
   \ V /  / __/ | |  	Email: deace.inc@gmail.com
    \_/  |_____||_|  	facebook.com/deace.inc
                     
"