#!/system/bin/sh
# V2T by Aditya Pratama :v
# Copyright (c) 2017 DEACE
version="1.1.10"
log=/dev/null

#Timelog
_time () {
	if [ "$1" = 0 ]; then
		echo -n "[$(date +%H:%M:%S)] "
	else
		echo >> "$log"
		echo "[$(date '+%d-%m-%y %H:%M:%S')]" >> "$log"
	fi
}

_tethering () {
	$@
	sleep 3
	_time 1
	iptables --flush &>> "$log"
	iptables -t filter -F FORWARD &>> "$log"
	iptables -t nat -F POSTROUTING &>> "$log"
	iptables -t filter -A FORWARD -j ACCEPT &>> "$log"
	iptables -t nat -A POSTROUTING -j MASQUERADE &>> "$log"
	_time 0
	echo "Mengatur DNS..."
	iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT --to "8.8.8.8" &>> "$log"
	ip rule add from "$8.8.8.8/24" lookup 61 &>> "$log"
	ip route add default dev "tun0" scope link table 61 &>> "$log"
	ip route add "8.8.8.8/24" dev "$interface" scope link table 61 &>> "$log"
	ip route add broadcast 255.255.255.255 dev "$interface" scope link table 61 &>> "$log"
	_time 0
	echo "Selesai..."
}

## END V2T FUNCTION"

# depan
echo " __     ______ _____ "
echo " \ \   / /___ \_   _|	VPN TO TETHER v$version"
echo "  \ \ / /  __) || |  	Author: Aditya Pratama"
echo "   \ V /  / __/ | |  	Email: deace.inc@gmail.com"
echo "    \_/  |_____||_|  	facebook.com/deace.inc"
echo "                     "
echo "  Cara menggunakan: v2t [wf/usb/bt] [OPSI] [...] ...."
echo "  -i <interface> : Interface tethering. "
echo "  -x <ip address> : IP Address tethering."
echo "  -c <config-file> : Lokasi konfigurasi (default: $HOME"
echo "  -l <enable/disable> : Pencatatan log eksternal (default: disabled)"
echo "  -p <dir> : Lokasi folder log."
echo "  -a <enable/disable> : Otomatis mengulangi (default: enabled)"
echo "  -d <dns> : alamat DNS."

# mengecek akses root
xpath="/system/xbin"
if [ -e "$xpath/id" ];
then
	path="$xpath"
else
	path="/system/bin"
	force_root="1"
fi

if [ "$($path/id -u)" != "0" ] && [ "$($path/id -u)" != "root" ] && [ "$force_root" != "1" ]; then
	echo
	echo "  [!] Maaf! Akses root diperlukan."
else
	echo
	echo
	exit
fi

#parse arguments
FUNC=`getopt -o ihxclpad: -l interface "$@"` || exit 1
eval set -- "$FUNC"
while true; do
	case "$1" in
	-h|--help)	jj; shift;;
	-i|--interface) echo "B:'$2'"; shift 2;;
	-c) echo;;
	--)	shift; break;;
	*)	echo "Mohon masukkan argumen"; exit 1;;
	esac
done
